package backend_api.Backend.Entity.invoice;

public enum InvoiceEventType {
    INVOICE_CREATED,
    INVOICE_DRAFT_SAVED,
    
    INVOICE_SENT,
    INVOICE_VIEWED,
    INVOICE_DOWNLOADED,
    
    PAYMENT_INITIATED,
    PAYMENT_COMPLETED,
    PAYMENT_FAILED,
    PARTIAL_PAYMENT_RECEIVED,
    
    INVOICE_DUE_SOON,
    INVOICE_OVERDUE,
    
    INVOICE_UPDATED,
    INVOICE_CANCELED,
    INVOICE_DELETED,
    
    PDF_GENERATED,
    PDF_REGENERATED,
    
    
    REMINDER_SENT,
    FINAL_NOTICE_SENT,
    
    CREDIT_NOTE_ISSUED,
    
    SYSTEM_ERROR,
    MANUAL_ADJUSTMENT
}
