package backend_api.Backend.Entity.payment;

public enum PaymentEventType {
  
    AUTHORIZATION_STARTED,
    AUTHORIZATION_SUCCEEDED,
    AUTHORIZATION_FAILED,
    
    CAPTURE_STARTED,
    CAPTURE_SUCCEEDED,
    CAPTURE_FAILED,
    
    PAYMENT_PENDING,
    PAYMENT_APPROVED,
    PAYMENT_REJECTED,
    PAYMENT_EXPIRED,
    PAYMENT_CANCELLED,
    
    INVOICE_GENERATED,
    INVOICE_SENT,
    
    REFUND_INITIATED,
    REFUND_COMPLETED,
    REFUND_FAILED,
    
    RETRY_ATTEMPTED,
    GATEWAY_ERROR,
    TIMEOUT_ERROR,
    
    
    
}
