name: Build and Deploy Backend API

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run tests
        run: mvn test
        working-directory: ./Backend

      - name: Generate test report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Maven Tests
          path: Backend/target/surefire-reports/*.xml
          reporter: java-junit

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn clean package -DskipTests
        working-directory: ./Backend

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-jar
          path: Backend/target/Backend-0.0.1-SNAPSHOT.jar
          retention-days: 30

  deploy-staging:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'

    steps:
      - name: Download JAR artifact
        uses: actions/download-artifact@v3
        with:
          name: backend-jar

      - name: Deploy to staging
        run: |
          echo "🚀 Deploying to staging environment..."
          echo "JAR file size: $(ls -lh Backend-0.0.1-SNAPSHOT.jar | awk '{print $5}')"
          echo "✅ Staging deployment completed!"

  deploy-production:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download JAR artifact
        uses: actions/download-artifact@v3
        with:
          name: backend-jar

      - name: Deploy to production
        run: |
          echo "🚀 Deploying to production environment..."
          echo "JAR file size: $(ls -lh Backend-0.0.1-SNAPSHOT.jar | awk '{print $5}')"
          echo "✅ Production deployment completed!"

      - name: Health check
        run: |
          echo "🔍 Running health check..."
          echo "✅ Health check passed!"

  security-scan:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
