name: Deploy to Staging

on:
  push:
    branches: [master]

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build JAR
        working-directory: ./Backend
        run: mvn -B -DskipTests clean package

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ secrets.EC2_PORT }} ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to Staging
        run: |
          # Clean up and stop staging services (scoped to app-staging project)
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.EC2_PORT }} ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "
            cd /home/ec2-user/app
            echo '🧹 Cleaning up staging ports...'
            # Remove legacy fixed-name containers (one-time cleanup)
            docker rm -f alertmanager grafana prometheus backend-api 2>/dev/null || true
            docker-compose -p app-staging -f docker-compose.yml down --remove-orphans 2>/dev/null || true
            docker container prune -f || true
            echo '✅ Ports cleaned!'
          "

          # Copy files to server
          JAR_FILE=$(find ./Backend/target -name "*.jar" -type f | head -1)
          scp -o StrictHostKeyChecking=no -P ${{ secrets.EC2_PORT }} "$JAR_FILE" ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/ec2-user/app/
          scp -o StrictHostKeyChecking=no -P ${{ secrets.EC2_PORT }} docker-compose.yml ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/ec2-user/app/
          scp -r -o StrictHostKeyChecking=no -P ${{ secrets.EC2_PORT }} Backend ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/ec2-user/app/

          # Start staging
          echo "🚀 Starting staging..."
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.EC2_PORT }} ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "
            cd /home/ec2-user/app
            docker-compose -p app-staging -f docker-compose.yml build backend
            docker-compose -p app-staging -f docker-compose.yml up -d
            echo '✅ Staging deployed!'
            echo 'Backend: http://localhost:8080'
            echo 'Grafana: http://localhost:3000'
          "
